// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5euL7EEPLkZzEacWcoUPUGRUFoguDf8A',
    appId: '1:87105368480:web:e17ce8f8bbe09edfa4b4c5',
    messagingSenderId: '87105368480',
    projectId: 'attendin-be3e2',
    authDomain: 'attendin-be3e2.firebaseapp.com',
    storageBucket: 'attendin-be3e2.firebasestorage.app',
    measurementId: 'G-JL4492DB7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrjWBnkYA7iSPuHNUdt5r8I-mur72BPRw',
    appId: '1:87105368480:android:7f2f949307c34a09a4b4c5',
    messagingSenderId: '87105368480',
    projectId: 'attendin-be3e2',
    storageBucket: 'attendin-be3e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIp9dTj52tIF5mycbb_768i8i1iLbMDOs',
    appId: '1:87105368480:ios:2ec1c83681c82138a4b4c5',
    messagingSenderId: '87105368480',
    projectId: 'attendin-be3e2',
    storageBucket: 'attendin-be3e2.firebasestorage.app',
    iosBundleId: 'com.mutazzzeidan.attendin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR050Lst_R7ZVGSeKIHn4krQQkpDJ3EqY',
    appId: '1:745942670373:ios:8809060ab741a65989b3cc',
    messagingSenderId: '745942670373',
    projectId: 'attendin-f79e9',
    storageBucket: 'attendin-f79e9.firebasestorage.app',
    iosBundleId: 'com.example.attendin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9LSLH2ukN1sY-EmYlkAhEBoGrhWerUc',
    appId: '1:745942670373:web:81c60e1ac514e3a989b3cc',
    messagingSenderId: '745942670373',
    projectId: 'attendin-f79e9',
    authDomain: 'attendin-f79e9.firebaseapp.com',
    storageBucket: 'attendin-f79e9.firebasestorage.app',
    measurementId: 'G-XNHN955PYD',
  );
}